# These are supported funding model platforms

ko_fi: maxchinni
custom: ['https://www.paypal.com/donate/?hosted_button_id=VNJW6ZLHPM23Q', 'https://explorer.btc.com/btc/address/bc1qt7p759pzzrqg2mj46p2k624uzcjg9xadhgftqh']
